### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#260]
I would like to release mnml / geometry 2. I do not have access to change the default branch.
- [ ] add "master / geometry 1 is deprecated" warning to master readme
- [x] change default branch from master to mnml on github
- [ ] cut github release
- [ ] announce on r/unixporn, r/zsh, r/linux
- [x] add deprecated.zsh github plugin which just says "please use the new mnml branch" on startup
Anything else? Should take about 1 hour total.

**Comment by jedahan** [comment]
Since its been quiet for almost a year, I plan on releasing `geometry-zsh/geometry:mnml` as `jedahan/mnml:mnml`, of course keeping the full history, having everyone credited in the readme, etc.

If there is still silence after a month, I plan on adding a warning to the readme that it is deprecated, and to find a new theme by looking at `jedahan/mnml` and `https://github.com/unixorn/awesome-zsh-plugins`.

If there is still silence after 2 months, I would ask to archive the repo.

**Comment by frm** [comment]
Regarding this and following this comment: https://github.com/geometry-zsh/geometry/issues/262#issuecomment-512937601

I intend getting back now and helping out on what I can, going back to be an active maintainer. However, you have been leading the development for this, so I would place any decision in your hands.

I've just given you admin rights to the repo (I didn't realize you did not have them). If you prefer to fork and move it to your account, I'm fine with that. Otherwise, we can change the default branch and go back to being active. Go through the checklist and re-release everything. It's a shame that I let things go by unnoticed.

Why not merge to master and assume this as a version 2 of geometry though?

**Comment by frm** [comment]
Any news @jedahan ?

**Comment by jedahan** [comment]
There are two minor reasons I thought changing the default branch was preferable to merging to master.

1. It means we can move away from `master/slave` terminology
2. It means we can update master to have a 'this is deprecated, please change branches or re-clone from scratch' forcing people to intentionally update to the new format since its such a huge break.

**Comment by jedahan** [comment]
Both reasons are small, so I'm fine just merging to master. It means it'll be a rough week for users though.

**Comment by frm** [comment]
Only for new updates, is that correct?

**Comment by jedahan** [comment]
Well anyone who does a `git pull` (which a lot of managers will do without versioning) will have their prompt change a decent amount - any customizations won't get picked up, etc.

**Comment by frm** [comment]
What this: we make `mnml` the default branch, add a changes.zsh file to the master branch and on the first time the users load it, it displays a warning. We leave it as it is for a while and then merge everything to master.

The users will have a heads up and we can go back to a normal git flow. We can also make a migration guide, maybe? For the variables we can have a markdown table saying what changed, for complex functionality maybe explaining the new system?

**Comment by jedahan** [comment]
I like that idea a lot. I'll make `changes.zsh` today and mnml the default branch. We can work on a migration guide on the wiki for now, and then copy it to the repo if necessary.

**Comment by frm** [comment]
Perfect! Is there anything you want me to do? I'd like to get things done before Tuesday, if needed.

PSA: I'll be offline from Aug 21 to Sep 2, vacationing. I'll try to reply as much as I can but I won't be able to do much in terms of code during that period.

**Comment by jedahan** [comment]
I'm also on vacation during this time, thanks for picking things back up!

I wrote a basic migration guide, changed `mnml` to the default branch, and we can give it a month before merging to master.

**Comment by jedahan** [comment]
Let's close this when we merge to master and announce then.

**Comment by jedahan** [comment]
Draft announcement:
---
geometry is a zsh prompt that is simple, fast, and easy to customize.

After a year of testing, we are happy to release geometry v2. Version 2 is a a complete rewrite of geometry that is easier to customize, is less than half the size, and has dozens of fixed bugs.

Any function that prints to standard out can be added to the left or right prompt, or the default 'enter' command. The right prompt render's asynchronously, so place long-running commands in `GEOMETRY_RPROMPT`.

geometry ships with 16 functions that only show up when appropriate - for example when in a git repo or using a non-default virtualenv for python.

More details and screenshots are in the readme, and any feedback is appreciated.

**Comment by frm** [comment]
I'm back. Just to be sure, looking at the checklist on the description of the issue, the next todo's would be to announce on socials, right?

Re: the announcement, can we use the gif we did before (or even make a new one?) and mention how to write your own plugins?

**Comment by jedahan** [comment]
Yep, its just 'post the announcement', with a gif. Which one were you thinking of using or re-making?

**Comment by frm** [comment]
Not sure, I still haven't fully upgraded so I don't know how close the gif is to the current reality. What's your take?

**Comment by jedahan** [comment]
I think the most compelling feature to share is that any function that prints can be easily added to the prompt.

**Comment by jedahan** [comment]
I'm ready to merge to master :)

**Comment by frm** [comment]
👍 just change the default branch, right? How can we go about socials and so?

**Comment by jedahan** [comment]
I'll post this announcement on r/zsh, r/unixporn and r/linux after changing the default branch sometime this week
---
# geometry v2 - a simple, customizable zsh prompt

geometry is a zsh prompt that is simple, fast, and easy to customize.

After a year of testing, we are happy to release geometry v2. Version 2 is a a complete rewrite of geometry that is easier to customize, is less than half the size, and has dozens of fixed bugs.

Any function that prints to standard out can be added to the left or right prompt, or the default 'enter' command. The right prompt renders asynchronously, so place long-running commands in the GEOMETRY_RPROMPT array.

geometry ships with 16 functions that only show up when appropriate - for example when in a git repo or using a non-default virtualenv for python.

More details and screenshots are in the readme, and any feedback is appreciated.

**Comment by jedahan** [comment]
posted to unixporn, will see shortly if it stays up and will cross-post to r/zsh

**Comment by jedahan** [comment]
cross-posted to r/zsh https://www.reddit.com/r/zsh/comments/eo6a0b/oc_geometry_zsh_prompt_customize_your_prompt_with/

**Comment by jedahan** [comment]
Thanks everyone who helped make this happen!

@frm
@desyncr 
@alxbl
@crasx
@diogoazevedos
@drager
@ev-agelos
@JokeNeverSoke
@Konsonanz
@MarioRicalde
@olegTarassov
